// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIcAoO1N1OF3QDPL6CKalKzSyoV9-i34',
    appId: '1:246322481984:web:9f5c8c92aed3825dc188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    authDomain: 'training-ea8b4.firebaseapp.com',
    storageBucket: 'training-ea8b4.appspot.com',
    measurementId: 'G-MX0C4NX61Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zltHp9n67nr2xMhdDgIdAB9pI_1pPII',
    appId: '1:246322481984:android:8270cae664440fb0c188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    storageBucket: 'training-ea8b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8nMaaDH4cZdcZTbhAfwdTuE9FZ9a2QI',
    appId: '1:246322481984:ios:1c6af6f16ecf5882c188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    storageBucket: 'training-ea8b4.appspot.com',
    iosBundleId: 'com.example.fcmTraning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8nMaaDH4cZdcZTbhAfwdTuE9FZ9a2QI',
    appId: '1:246322481984:ios:1c6af6f16ecf5882c188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    storageBucket: 'training-ea8b4.appspot.com',
    iosBundleId: 'com.example.fcmTraning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDIcAoO1N1OF3QDPL6CKalKzSyoV9-i34',
    appId: '1:246322481984:web:a13b935339dbab4dc188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    authDomain: 'training-ea8b4.firebaseapp.com',
    storageBucket: 'training-ea8b4.appspot.com',
    measurementId: 'G-4FS7QLXLPX',
  );
}
